apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ec-u7lo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/partner-catalog-ec/partner-catalog-ec-u7lo@sha256:d8c813ccee9c2867483a84ce4eb410f6a89e2c186df84c6ff3b65c7bbcab7a78
        name: my-java-springboot
        resources: {}
status: {}
