apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-ec-u7lo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/partner-catalog-ec/partner-catalog-ec-u7lo@sha256:ee90a4a1fa914d40db16dddc222dc68c3914f66d8418ccfa0c95a6eb9bffe81d
        name: my-java-springboot
        resources: {}
status: {}
