apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog-ec-u7lo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog-ec-u7lo
    app.kubernetes.io/part-of: partner-catalog-ec
  name: partner-catalog-ec-u7lo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog-ec-u7lo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog-ec-u7lo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-csears-tenant/partner-catalog-ec/partner-catalog-ec-u7lo@sha256:a8dc6a22ac65c9c7dd023959975492b15804f618c388505e6dec0ccfc22afafe
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
